### ISSUE TITLE
[Help wanted] How to LDAP Attribute mapping for email?

### ISSUE THREAD

**Issue by tertek** [grezniczek/redcap_survey_auth#12]
I have tested the module successfully with tabled-based authentication on a local REDCap instance. After auth, I only need username and email, which are returned for table-based.

Now I am testing on our DEV instance, where we have table-based and LDAP auth. Unfortunately, I was unable to retrieve the email address of the user after successful login. I am unsure which value I have to enter into the LDAP attribute mapping. Based on the LDAP config, where can I find out the correct value name for mapping to email?

**Comment by tertek** [comment]
REDCap 14.0.9 · PHP 8.2.15 (Linux/Unix OS) · MariaDB 10.5.22
Survey Auth - v1.4.5

**Comment by grezniczek** [comment]
@tertek - LDAP is notoriously difficult .... talk to your LDAP / AD admin guys to find out what attributes you need to query.

The LDAP Troubleshooter in REDCap can help.
![image](https://github.com/grezniczek/redcap_survey_auth/assets/25482666/9779d481-3697-4d42-8a6f-669960a006b6)

**Comment by tertek** [comment]
It seems as if there is no Email Address being passed during LDAP Login. I suppose user_email is stored during initial login into user redcap_user_info and never touch again afterwards.

I wonder if it would be possible to grab user data from redcap_user_info also when LDAP is chosen.

**Comment by grezniczek** [comment]
@tertek - Check the code in _SurveyAuthExternalModule.php_ in the `doLDAPauth()` function after line 560.
Email is something that should be retrievable via the attributes. How to get these attributes delivered is something you need to figure out for your specific LDAP environment. If the names do not match, then the module might need to be extended to do some name mapping (via addditional config settings).

The redcap_user_info table would only help for users who are already known to REDCap (i.e., those who have an account). In that case, why use survey auth when they can just log in to a regular project/data entry form?

**Comment by tertek** [comment]
@grezniczek I have been confirmed by our IT that there is no email being transferred during LDAP Login. 

The only way for us to retrieve Email would be through `redcap_user_info table`.

> why use survey auth when they can just log in to a regular project/data entry form
For internal processes that should be accessible through a public survey only for users in our AD. Using a data entry form would imply that these users access it within REDCap which is not wanted here.

**Comment by grezniczek** [comment]
@tertek - Your IT is wrong, or this is a specific limitation of the LDAP setup at your institution.

Make sure to **specify the needed attributes** in your LDAD config (either REDCap's _ldap_config.php_ or the custom config in the module settings). E.g.,
```php
$GLOBALS['ldapdsn'] = array(
    'url'        => 'ldap://aaa.bbb.ccc.ddd',
    'port'       => 389,
    'version'    => 3,
    'basedn'     => 'whatever',
    'binddn'     => 'user',
    'bindpw'     => 'password',
    'attributes' => array('mail'),
    'userattr'   => 'samaccountname',
    'userfilter' => '(objectCategory=person)',
    'referrals'  => false
);
```

If the email attribut differs from "mail" or "email", be sure to specify the mapping in the module's config:

![image](https://github.com/grezniczek/redcap_survey_auth/assets/25482666/244e5fe7-894c-4c3a-97ac-f7bacf774e78)


This works fine with our LDAP here. I am able to retrieve the email address of users who do **_not_** have a REDCap account.

**Comment by grezniczek** [comment]
To add to the previous post: Replace "mail" (in the attributes array) with whatever fits your LDAP. It might be "email" or "emailAddress" (in the latter case: add the mapping in the module config). 

If your LDAP cannot provide attributes (or does not store users' email addresses), then going via _redcap_user_info_ would be a (limited) workaround (everybody would need to register a REDCap account).

If you want that, feel free to provide a PR that implements this.

I would make it a configuration option, such as a checkbox labeled **"Use email stored by REDCap when not obtainable from LDAP attributes"**. When checked, the code could try to find an email address in **redcap_user_info**.

**Comment by tertek** [comment]
@grezniczek 
> or this is a specific limitation of the LDAP setup at your institution.
Indeed, it is an explicit guideline. Therefore, on initial (valid) login each user is presented with the "Basic User Information form" which then stores relevant data into redcap_user_info.

It seems like the workaround is our only way to go for us.
Thank you for being open for the PR.

**Comment by grezniczek** [comment]
(Hopefully) Resolved via https://github.com/grezniczek/redcap_survey_auth/commit/427440772c6783546ccd3962351b9b57ae27799c
