### ISSUE TITLE
API interface won't set value on record creation

### ISSUE THREAD

**Issue by pbchase** [grezniczek/redcap_survey_auth#3]
@grezniczek, we've been trying out this module today and our customer really like it.  Thanks so much for this. 

I am writing because we are having an issue getting the API to write data as it creates the new record. We can authenticate, and API code creates the record, but it won't write the username value into the redcap field. This is with a RC 9.3.5, version 1.2.5 of your module, and custom field authentication. 

I've attached an export of my test project at [SurveyAuthTest1_2020-03-27_1532.REDCap.xml.zip](https://github.com/grezniczek/redcap_survey_auth/files/4395579/SurveyAuthTest1_2020-03-27_1532.REDCap.xml.zip) My module config looks like this:

![module config 1](https://user-images.githubusercontent.com/3356493/77793568-af54a780-7040-11ea-808c-5e8980635dc3.png)

![module config 2](https://user-images.githubusercontent.com/3356493/77793557-a8c63000-7040-11ea-8bb5-d21683167124.png)

Am I just not reading the docs right?

**Comment by grezniczek** [comment]
@pbchase thanks for reporting this. You did everything right. It was indeed a bug. [v1.2.6](https://github.com/grezniczek/redcap_survey_auth/releases/tag/v1.2.6) provides a fix. Should show up in the Repo shortly, or you can grab it from here.

**Comment by pbchase** [comment]
Thanks, @grezniczek, that fixed it. We now have this in production.

**Comment by grezniczek** [comment]
Out of interest, @pbchase, are you using it with "Custom" authentication only (as in the example you provided, or have you used it with LDAP as well? 
I am asking, as LDAP seems to be quite tricky, and some get it to work in their environments and some don't. So I am looking for hints what might be the deciding (and hopefully common) factor ...

**Comment by pbchase** [comment]
We are only using your _custom_ auth. Sorry, no LDAP.

**Comment by grezniczek** [comment]
Ok. Thanks for letting me know.
