### ISSUE TITLE
Configure Module Survey Auth User cannot access now

### ISSUE THREAD

**Issue by johnston1** [grezniczek/redcap_survey_auth#5]
Works previously, but last 2 days when user tries to configure auth it just keeps spinning. Tried explorer and chrome. RECap version 10.5.1 module version 1.2.7.
Module works for other users.
j.johnston@ufl.edu

**Comment by grezniczek** [comment]
@johnston1  Is this still an issue? 

(I forgot to turn on notification for this repo and only saw your issue now)

**Comment by grezniczek** [comment]
Closing this.
