### ISSUE TITLE
$_SERVER["REQUEST_SCHEME"] is unreliable in reporting scheme, resulting in inability to submit the form

### ISSUE THREAD

**Issue by AndrewPoppe** [grezniczek/redcap_survey_auth#9]
@grezniczek 
We are getting a form action with "http://" instead of "https://".

I am not sure what the solution should be, since it seems v1.2.8 changed the url construction away from what my suggestion would be (using APP_PATH_SURVEY_FULL).

**Comment by grezniczek** [comment]
@AndrewPoppe 
Thanks for letting me know.

I have changed this to (again) use `APP_PATH_SURVEY_FULL`, as you suggest.
I think the reason to change this was to support prefilling of survey fields via url parameters (which must be channeled through to the actual survey).

Please try the new release https://github.com/grezniczek/redcap_survey_auth/releases/tag/v1.3.1. Submitting to the EM Repo now, too.

**Comment by AndrewPoppe** [comment]
It's working like a charm. Great stuff @grezniczek

**Comment by grezniczek** [comment]
@AndrewPoppe , that's great to hear!
